# Permalinks
permalink:           pretty

# Setup
title:              'RUSMALAI Math Workshop'
tagline:             '(Informal)'
url:                 'https://abstractgeek.github.io/rusmalai-math-workshop/'
paginate:            1
baseurl:             "https://abstractgeek.github.io/rusmalai-math-workshop/"

markdown:           kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              AbstractGeek
  url:               https://abstractgeek.github.io/

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/AbstractGeek/rusmalai-math-workshop

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
