# Permalinks
permalink:           pretty

# Setup
title:              'RUSMALAI Math Workshop'
description:         'Informal math workshop @ NCBS'
url:                 'https://abstractgeek.github.io/'
paginate:            5
baseurl:             "rusmalai-math-workshop/"
twitter_username:    abstractgeek42
github_username:    abstractgeek42
markdown:           kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              AbstractGeek
  url:               https://abstractgeek.github.io/

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/AbstractGeek/rusmalai-math-workshop

plugins: [jekyll-paginate, kramdown]
